version: "3"
services:
  app:
    build:
      context: .
      args:
        rails_environment: development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app/
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    links:
      - redis
      - job
  redis:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379"
    volumes:
      - ./cache_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
  job:
    image: 'redis:6.0-alpine'
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass tableworkpassword
    ports:
      - "6379"
    volumes:
      - ./job_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  bundler_gems:      
