# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'bcrypt', '~> 3.1.18'
gem 'puma', '>= 5.6.0'
gem 'net-smtp'
gem 'rails', '~> 7.0.3'
gem 'railties', '~> 7.0.3'
gem 'rails-i18n', '~> 7.0'
gem 'sdoc', '~> 2.4', group: :doc
gem 'rdoc', '>= 5.0'
gem 'sqlite3', '~> 1.4.4'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.12', require: false

gem 'pg', '>= 1.4'
gem 'redis', '>= 4.7'
gem 'seed_dump'
gem 'sidekiq', '~> 6.5'
gem 'sprockets-rails', '~> 3.4', require: 'sprockets/railtie'

gem 'pundit', '~> 2.2'

gem 'whenever', '~> 1.0', require: false
gem 'json', '~> 2.6.2'
gem 'rest-client', '~> 2.1'

gem 'kaminari', '~> 1.2.2'
gem 'will_paginate','~> 3.3'

platforms :ruby do # linux
  gem 'libv8'
end

gem 'rspec-rails', '~> 5.0'
gem 'rswag'
gem 'rack-cors'
gem 'jbuilder'

group :development do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 11.1.3'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'listen', '>= 3.7.1'
end

group :test do
  gem 'capybara', '~> 3.36'
  gem 'rubyzip', '~> 2.3.2'
  gem 'webdrivers', '~> 5.0'
  gem 'factory_bot_rails', '~> 6.2.0'
  gem 'rails-controller-testing'
end
