---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/access_roles":
    post:
      summary: Creates an access_role
      tags:
      - AccessRoles
      parameters: []
      responses:
        '201':
          description: Access Role created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                rid:
                  type: string
                user_ids:
                  type: array
                  items:
                    type: integer
              required:
              - name
              - rid
  "/access_roles/{id}":
    get:
      summary: Retrieves an access role
      tags:
      - AccessRoles
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: access role found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  rid:
                    type: string
                  users:
                    type: array
                    items:
                      type: object
                      items:
                        type: string
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  rid:
                    type: string
                  users:
                    type: array
                    items:
                      type: object
                      items:
                        type: string
                required:
                - id
        '404':
          description: access role not found
        '406':
          description: unsupported accept header
  "/job_types":
    post:
      summary: Creates a job type
      tags:
      - JobTypes
      parameters: []
      responses:
        '201':
          description: Job type created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                code:
                  type: string
                light_color:
                  type: string
                dark_color:
                  type: string
                user_ids:
                  type: array
                  items:
                    type: integer
              required:
              - name
              - code
  "/job_types/{id}":
    get:
      summary: Retrieves a job type
      tags:
      - JobTypes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: job type found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  code:
                    type: string
                  light_color:
                    type: string
                  dark_color:
                    type: string
                  users:
                    type: array
                    items:
                      type: object
                      items:
                        type: string
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  code:
                    type: string
                  light_color:
                    type: string
                  dark_color:
                    type: string
                  users:
                    type: array
                    items:
                      type: object
                      items:
                        type: string
                required:
                - id
        '404':
          description: job type not found
        '406':
          description: unsupported accept header
  "/shifts":
    post:
      summary: Creates a shift
      tags:
      - Shifts
      parameters: []
      responses:
        '201':
          description: Shift created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                department:
                  type: string
                color:
                  type: string
                startdate:
                  type: string
                enddate:
                  type: string
                user_id:
                  type: string
                shop_id:
                  type: string
              required:
              - name
              - startdate
              - enddate
              - user_id
              - shop_id
    get:
      summary: List shifts
      tags:
      - Shifts
      responses:
        '201':
          description: Shifts list
  "/shifts/{id}":
    get:
      summary: Retrieves a shift
      tags:
      - Shifts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: shift found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  department:
                    type: string
                  color:
                    type: string
                  startdate:
                    type: string
                  enddate:
                    type: string
                  user_id:
                    type: string
                  shop_id:
                    type: string
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  department:
                    type: string
                  color:
                    type: string
                  startdate:
                    type: string
                  enddate:
                    type: string
                  user_id:
                    type: string
                  shop_id:
                    type: string
                required:
                - id
        '404':
          description: shift not found
        '406':
          description: unsupported accept header
  "/shops":
    post:
      summary: Creates a shop
      tags:
      - Shops
      parameters: []
      responses:
        '201':
          description: Shop created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                user_ids:
                  type: array
                  items:
                    type: integer
              required:
              - name
    get:
      summary: List shops
      tags:
      - Shops
      responses:
        '201':
          description: Shops list
  "/shops/{id}":
    get:
      summary: Retrieves a shop
      tags:
      - Shops
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: shop found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  shifts:
                    type: array
                    items:
                      type: object
                      items:
                        type: string
                  users:
                    type: array
                    items:
                      type: object
                      items:
                        type: string
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  shifts:
                    type: array
                    items:
                      type: object
                      items:
                        type: string
                  users:
                    type: array
                    items:
                      type: object
                      items:
                        type: string
                required:
                - id
        '404':
          description: shop not found
        '406':
          description: unsupported accept header
  "/users":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: User created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                address:
                  type: string
                phone:
                  type: string
                photo_url:
                  type: string
                job_type_id:
                  type: string
                shop_id:
                  type: string
                access_role_id:
                  type: integer
                shift_ids:
                  type: array
                  items:
                    type: integer
              required:
              - name
              - email
              - access_role_id
    get:
      summary: List users
      tags:
      - Users
      responses:
        '201':
          description: Users list
  "/users/{id}":
    get:
      summary: Retrieves a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: user found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  address:
                    type: string
                  phone:
                    type: string
                  photo_url:
                    type: string
                  job_type_id:
                    type: string
                  shop_id:
                    type: string
                  access_role_id:
                    type: integer
                  shifts:
                    type: array
                    items:
                      type: object
                      items:
                        type: string
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  address:
                    type: string
                  phone:
                    type: string
                  photo_url:
                    type: string
                  job_type_id:
                    type: string
                  shop_id:
                    type: string
                  access_role_id:
                    type: integer
                  shifts:
                    type: array
                    items:
                      type: object
                      items:
                        type: string
                required:
                - id
        '404':
          description: user not found
        '406':
          description: unsupported accept header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: tablework.vectorsigma.ru
- url: http://localhost:3000
