development:
  adapter: redis
  url: redis://redis:6379/1

test:
  adapter: async

staging:
  adapter: redis
  url: redis://:<%= Rails.application.credentials[:redis_cache_password] %>@redis:6379/1

production:
  adapter: redis
  url: redis://:<%= Rails.application.credentials[:redis_cache_password] %>@redis:6379/1
  channel_prefix: tablework_production
